import type { Metadata } from "next";
import Link from "next/link";
import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import { SITE_NAME, SITE_URL } from "@/lib/seo";

const LAST_UPDATED = "2026-05-29";

export const metadata: Metadata = {
  title: "AI Use",
  description:
    "What Owlka's AI can and cannot do, in plain English. AI replies can be wrong, and Claude has deep control of your Mac. Read this before you start.",
  alternates: { canonical: "/ai-use" },
  openGraph: {
    type: "article",
    siteName: SITE_NAME,
    url: `${SITE_URL}/ai-use`,
    title: "AI Use",
    description:
      "What Owlka's AI can and cannot do, in plain English. AI replies can be wrong, and Claude has deep control of your Mac.",
    locale: "en_US",
  },
  twitter: {
    card: "summary",
    title: "AI Use",
    description:
      "What Owlka's AI can and cannot do, in plain English. AI replies can be wrong, and Claude has deep control of your Mac.",
  },
};

type Row = { label: string; value: string };

type Section = {
  id: string;
  title: string;
  intro?: string;
  rows: Row[];
  footnote?: string;
};

const SECTIONS: Section[] = [
  {
    id: "what-it-is",
    title: "What Owlka is",
    intro:
      "Owlka pairs your iPhone with your own Mac so you can drive Claude Code from the sofa. The replies you see in the app are written by Claude, running on your Mac under your own Anthropic login. Owlka is the screen and the keyboard; Claude does the thinking and the work.",
    rows: [
      {
        label: "Claude writes the replies",
        value:
          "Every answer, plan, and line of code you see in Owlka is generated by Claude, an AI model from Anthropic. Owlka does not write the replies and does not check them for accuracy.",
      },
      {
        label: "It runs on your machine",
        value:
          "Claude runs on your own Mac under your own Claude subscription. Your code, your files, and your project memory stay on your Mac. Owlka never copies them to a server.",
      },
    ],
  },
  {
    id: "hallucinate",
    title: "Risk 1: AI can be wrong",
    intro:
      "This is the most important thing to understand before you rely on anything Owlka tells you.",
    rows: [
      {
        label: "AI tools hallucinate and make mistakes",
        value:
          "Claude, like every large language model, can produce answers that sound confident and are simply wrong. It can invent facts, cite sources that do not exist, write code that looks right but does not work, and misunderstand what you asked. Treat every reply as a draft, not a final answer, and verify anything that matters.",
      },
      {
        label: "Not professional advice",
        value:
          "Owlka is not for medical, legal, financial, or any other professional advice. Do not act on a reply that affects your health, your money, your legal position, or anyone's safety without checking it with a qualified human.",
      },
      {
        label: "You are responsible for what you ship",
        value:
          "If you use Owlka to write code, send a message, change a file, or make a decision, the outcome is yours. Review the work before you act on it, exactly as you would review work from a junior colleague.",
      },
    ],
  },
  {
    id: "machine-control",
    title: "Risk 2: Claude has deep control of your Mac",
    intro:
      "Owlka is not a chatbot in a sandbox. Claude Code can run real commands on your real machine. That is the whole point of the product, and it is also the biggest risk.",
    rows: [
      {
        label: "Claude can change and delete files",
        value:
          "Claude Code can read, create, edit, move, and delete files on your Mac, run terminal commands, install software, and make network requests. A mistaken or misunderstood instruction can damage your work, including deleting files or directories. This can happen even when you meant well, because the AI can misjudge what you wanted.",
      },
      {
        label: "Used at your own risk",
        value:
          "You run Owlka, and the Claude tools it launches, at your own risk. Owlka cannot guarantee that Claude will only do what you intended. Keep good backups of anything you cannot afford to lose, and do not point Owlka at a machine or a folder where an accidental deletion would be a disaster.",
      },
      {
        label: "Safety rails help but do not remove the risk",
        value:
          "Claude asks before some risky actions, and you can run reviewer agents on your Mac that read each change before it lands. These reduce the chance of a bad action slipping through, but they do not make Owlka safe to use without paying attention. The final responsibility for what runs on your Mac is yours.",
      },
    ],
  },
  {
    id: "how-to-use-safely",
    title: "Using Owlka sensibly",
    intro:
      "None of the above means Owlka is dangerous to use day to day. It means you should use it the way a careful developer uses any powerful tool.",
    rows: [
      {
        label: "Keep backups",
        value:
          "Use Time Machine or another backup so a bad deletion is an inconvenience, not a catastrophe.",
      },
      {
        label: "Use version control",
        value:
          "Work inside a Git repository where you can review and undo changes before they become permanent.",
      },
      {
        label: "Read before you approve",
        value:
          "When Claude proposes a change or asks to run a command, read it. The pause is there so you can catch a mistake before it happens.",
      },
      {
        label: "Verify anything important",
        value:
          "Before you rely on a fact, a figure, or a piece of code, check it. AI confidence is not the same as AI correctness.",
      },
    ],
  },
  {
    id: "privacy",
    title: "Privacy and your data",
    intro:
      "Owlka is built so the company never sees your work. The detail lives on the privacy and security pages; the short version is below.",
    rows: [
      {
        label: "End-to-end encrypted",
        value:
          "Messages between your phone and your Mac are encrypted on the sending device before they leave it. Our relay forwards sealed packets and cannot read them. We do not hold the keys.",
      },
      {
        label: "No training on your work",
        value:
          "Owlka does not train any model on your prompts, your code, or the work Claude produces for you. Your use of Claude itself is governed by your own agreement with Anthropic.",
      },
      {
        label: "Anthropic sees what Claude sees",
        value:
          "Claude runs under your own Anthropic account and talks to Anthropic directly. Whatever you send to Claude reaches Anthropic under their terms, not ours.",
      },
    ],
  },
  {
    id: "age",
    title: "Age rating",
    rows: [
      {
        label: "Rated 17+",
        value:
          "Owlka is rated 17+ on the App Store because Claude can discuss any topic you ask about. Decide whether that is right for you before you start.",
      },
    ],
  },
];

export default function AIUsePage() {
  return (
    <>
      <Nav />
      <main className="min-h-screen bg-bg text-text">
        <div className="mx-auto max-w-3xl px-6 pt-32 pb-24 sm:pt-40 sm:pb-32">
          <header className="mb-10">
            <Link
              href="/"
              className="text-sm text-muted hover:text-text transition-colors"
            >
              &larr; Back to Owlka
            </Link>
            <h1 className="mt-4 text-4xl font-semibold tracking-tight">
              AI Use
            </h1>
            <p className="mt-3 text-muted">
              Last updated {LAST_UPDATED}. Owlka is powered by Claude, an AI
              model. This page explains, in plain English, what that means
              for you: where the AI can get things wrong, and how much
              control it has over your Mac. Please read it before you start.
            </p>
          </header>

          <nav
            aria-label="On this page"
            className="mb-12 rounded-[18px] border border-border bg-surface p-5 text-sm"
          >
            <p className="mb-3 font-medium">On this page</p>
            <ul className="space-y-1.5">
              {SECTIONS.map((s) => (
                <li key={s.id}>
                  <a
                    href={`#${s.id}`}
                    className="text-muted hover:text-text transition-colors"
                  >
                    {s.title}
                  </a>
                </li>
              ))}
            </ul>
          </nav>

          {SECTIONS.map((section) => (
            <section
              key={section.id}
              id={section.id}
              className="mb-14 scroll-mt-16"
            >
              <h2 className="text-2xl font-semibold tracking-tight">
                {section.title}
              </h2>
              {section.intro && (
                <p className="mt-3 text-muted leading-relaxed">
                  {section.intro}
                </p>
              )}

              <dl className="mt-6 rounded-[18px] border border-border bg-surface">
                {section.rows.map((row, i) => (
                  <div
                    key={row.label}
                    className={`grid gap-2 p-6 sm:grid-cols-[14rem_1fr] sm:gap-8 ${
                      i > 0 ? "border-t border-border" : ""
                    }`}
                  >
                    <dt className="font-medium">{row.label}</dt>
                    <dd className="text-muted leading-relaxed">{row.value}</dd>
                  </div>
                ))}
              </dl>

              {section.footnote && (
                <p className="mt-3 text-xs text-muted leading-relaxed">
                  {section.footnote}
                </p>
              )}
            </section>
          ))}

          <footer className="mt-16 border-t border-border pt-6 text-sm text-muted">
            <p>
              Want the detail on how the encryption works? See{" "}
              <Link
                href="/security"
                className="underline hover:text-text transition-colors"
              >
                Security
              </Link>{" "}
              and{" "}
              <Link
                href="/how-it-works"
                className="underline hover:text-text transition-colors"
              >
                How it works
              </Link>
              . Questions? Email{" "}
              <a
                href="mailto:support@owlka.com"
                className="underline hover:text-text transition-colors"
              >
                support@owlka.com
              </a>
              .
            </p>
          </footer>
        </div>
      </main>
      <Footer />
    </>
  );
}
